### ISSUE TITLE
Question - page background color

### ISSUE THREAD

**Issue by gdmccarty** [PeterWone/vsc-print#107]
First, the extension is great!  Appreciate the effort.

Question - Out of the box, when I print (using the default atelier-dune-light.css stylesheet), the code is rendered in a 'beige' box.  I wanted to print in color on a white background (to save ink).  I edited the style sheet, and change the background attribute in .hljs to white.  Seems to be fine.

Is this the correct way to do this? Would it be better to dup the stylesheet and change that?
Thanks.

**Comment by PeterWone** [comment]
Excellent question.

Editing the stylesheet won't cause problems. The reason I never change them is they are supplied by the highlightjs library that I use for syntax colouring, and changes would be clobbered whenever this gets a version bump. For this reason it's probably better to copy to another name. That way an update won't clobber your change.

**However...** in support of containers like docker and WSL, I am considering removing the ability to import stylesheets because I want them inside the bundle where they continue to be available when the filesystem is redirected to a container.

This would clash with using one's own stylesheet. 

What to do? Pending a better solution, in the print dialog of most browsers there is a checkbox controller whether background graphics is to be printed. Turning it off should have the effect you seek.

## Edge

![image](https://user-images.githubusercontent.com/5498936/128958315-8f42b728-987c-4651-978e-602bbaabc6e9.png)

## Chrome

![image](https://user-images.githubusercontent.com/5498936/128958385-36cfd5ea-8a3c-4dfe-ba3e-b6c142cab195.png)

## Firefox

I think this is the default for FF.

**Comment by gdmccarty** [comment]
Sounds great!  Thanks.
