### ISSUE TITLE
Local Image Files Not Rendering

### ISSUE THREAD

**Issue by ebromberg** [PeterWone/vsc-print#110]
I made a link to a local image file. It will render the image just fine in VSCode but when I goto Print, Chrome opens and it just spins. If I take the image out of the markdown, Chrome renders it and the print dialog box comes up just fine. 

This is the link in the markdown:
![testing](testimage.png)

And my version of Chrome is:
Version 93.0.4577.82 (Official Build) (64-bit)

**Comment by PeterWone** [comment]
Thank you for your patience. This latest release contains extensive changes to the way files are resolved in order to support remote hosts and this is almost certainly a casualty of those changes. If you'll bear with us I will try to resolve this now but please understand that it is nearly midnight here in Australia so it might be a next day thing.

**Comment by PeterWone** [comment]
I've found and fixed the problem, but now I have to update the change log plus there are pending changes to the manual that have to be translated into various languages so it might be another hour before the fix becomes available. When you are satisfied that your issue has been resolved, don't forget to close it. And maybe even consider writing a review.

**Comment by PeterWone** [comment]
And there it is, 0.9.12 is available.

**Comment by ebromberg** [comment]
Thank you very much for the quick turnaround. I just installed 0.9.12 and everything is working perfectly!
