### ISSUE TITLE
Wrapping of an indented line isn't indented

### ISSUE THREAD

**Issue by Shu-Ting-Huang** [PeterWone/vsc-print#125]
When I have a long indented line in my code, its wrapping is not indented as it is shown on screen. (`alt`+`z` to toggle the on-screen line wrapping)

Here are some examples:
<img width="918" alt="python" src="https://user-images.githubusercontent.com/57234743/148660975-fc464ad1-a2d4-4787-a829-3ad1a451d8b2.png">
<img width="918" alt="java" src="https://user-images.githubusercontent.com/57234743/148660976-6c115f4b-904b-45b7-9e3a-d0677637233c.png">
<img width="800" alt="cpp" src="https://user-images.githubusercontent.com/57234743/148660977-ee63c5c4-4c9d-44c2-a260-a24af7b2de07.png">.

This issue get more bizarre when my code is html with `src="some-long-URL"` (line 12 ine the following video clip). When the printing size is above some threshold, a (non-scrollable) scrollbar shows up at the bottom.

https://user-images.githubusercontent.com/57234743/148661125-173eff7d-2289-4080-9acc-8596914606f6.mp4

**Comment by PeterWone** [comment]
What browser is that?

**Comment by Shu-Ting-Huang** [comment]
> What browser is that?

Chrome (incognito mode).

**Comment by PeterWone** [comment]
Oh I see, it's in the Chrome print settings after you click "More settings". Thanks, now I can reproduce the issue.

# Indents on Wrapped Lines
The wrapped lines are not indented by design. This is because when line numbers are not displayed (that's an option) there would be no way to distinguish explicit whitespace from a hanging indent.


# Long URLs and scrollbars
Long URLs, or indeed any long string that does not contain a natural break as defined by the HTML spec will force the width of its container to grow. It's not so much that using a larger scale breaks things, it's more that using a smaller scale can fix them. 

This is an inherent limitation of using a browser to print and the browser is doing exactly what the spec requires. 

You could take it up with the HTML working group... only kidding, neither of us would live long enough to see an answer. More seriously it might be possible to check for long strings and inject soft-break characters whenever there is a run of more than say 50 characters without a candidate break. I'll look into that. Could take a while, I'll have to read the HTML spec in mind-numbing detail and there's no guarantee that it supports this solution.

**Comment by PeterWone** [comment]
Allowing breaks anywhere produces terrible wrapping so I can't use that approach. I'll have to scan to long strings that lack break candidate positions and split them with `<wbr>`
