### ISSUE TITLE
Few fixes

### ISSUE THREAD

**Issue by UPL123** [PeterWone/vsc-print#134]
* Change every `.es.md` file to `.esp.md`  or change every reference to `esp` in the code to `es`
* Add left languages in manual files
(From this)
[ENGLISH]() | [FRENCH]() | [GERMAN]() | [Add a language]()
(To this)
[ENGLISH]() | [FRANCAISE]() | [DEUTSCH]() | [ESPAGNOLE]() | [中文CHINESE]() | [Add a language]()

**Comment by PeterWone** [comment]
Good catch. I fixed all the es to esp changes in code but I forgot about filenames.

There have been a few changes in the manual, mostly things that have been removed because they were workarounds for remoting. 

When you translate the manual, I think probably you could completely omit this part because it's about a common misuse of the word "font" so really it only applies to people who are using English. Or you could rewrite it completely; the point of this is to explain terms as you have applied them to the UI.

> "Fira Code" is a typeface, not a font. "Fira Code 12pt Bold" is a font. Italic is a _treatment_ and Bold is a _weight_. Yes, I know you download font files. In the days before TrueType there was a separate file per size and treatment combination and it really was a font file. "Scalable font" is a contradiction in terms.

**Comment by UPL123** [comment]
Ok, thank you!

**Comment by PeterWone** [comment]
Have a look now. I've addressed the issues you raised plus I noticed printing of a selection was broken, so that's fixed too. I'm closing this issue; if you spot anything else raise a new issue. I strongly recommend you update your fork with the latest code; the code is much better organised, and there are minor changes to the manual that you'll want to incorporate into your translation.

I'd like to take the opportunity to congratulate you on the quality of your submission; I didn't have to do anything, it just worked.
