### ISSUE TITLE
Vowels Support

### ISSUE THREAD

**Issue by ac-webdesign** [PeterWone/vsc-print#21]
The actually Problem is that when you have vowels for example ä, ö, ü, that they are shown false.
It looks like that vsc-print not have utf 8 with vowel support.

![image](https://user-images.githubusercontent.com/43271236/56740081-7cd76600-6770-11e9-9d93-0a2045050153.png)

Thanks for an answer

**Comment by PeterWone** [comment]
I believe you have identified a bug.

Because my language (English) does not require any of those symbols and I do not live in Europe, none of my test cases involved extended character sets.

Happily this should be trivial to correct. 

I will also look into your other issue to decide whether to release a quick fix for UTF-8, or fix the image problem as well in the same release.

**Comment by ac-webdesign** [comment]
@PeterWone Thanks for the fast answer.

**Comment by PeterWone** [comment]
Added `<!DOCTYPE html>` and `<meta charset="utf-8"/>` to the generated HTML, and now extended character sets are honoured in the sample you provided. Publishing in 0.6.9
