### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by PeterWone** [PeterWone/vsc-print#28]
@natkuhn Do you think it's worth populating the wiki, and are you interested in handling this?

**Comment by natkuhn** [comment]
@PeterWone I am not sure which wiki you are talking about, but unfortunately I am not able to devote any more time to this at this point. I appreciate what you have done! My only remaining thought is that instead of a setting to control raw vs formatted printing, you could just have a "Print raw" command. But I appreciate that you may not be looking for extra things to do either! Thanks for a great project.
