### ISSUE TITLE
Respect code folding

### ISSUE THREAD

**Issue by PeterWone** [PeterWone/vsc-print#53]
It may be useful to be able to respect code folding when printing from an editor window. This is, however, an edge case requiring a significant investment of effort.

Indicate your level of interest to help me decide whether to bother.

**Comment by Hazaels** [comment]
Hi Peter, indeed it will require a significant investment of time and dedication but I am very interested.
The possibility of printing with the same colors you see on the editor is really good.
Of course the editor has a black background and the paper is white so it will require special care to preserver the color schema but use the proper replacements for certain details (for example the characters are white on VSCode but in paper they should be black) but for other colors it should not be a problem since anything different than white will be well seem in a white background (as a paper).
Thank you!

**Comment by PeterWone** [comment]
I avoided entirely the problems of mapping colours from dark screen to white paper by supporting a completely independent stylesheet for printing. I did tackle the problem, but the complexity of maintaining both colour scheme _and_ relative contrast levels was more  trouble than it was worth when people change their screen theme but paper is always white &mdash; so I simply support a stylesheet for printing that is completely independent of the stylesheet used for the screen.

**Comment by Hazaels** [comment]
Yes, you are right.
Since the paper is always white does not make sense to use so much energy.
Your solutions seems to be the best one.
Thank you

**Comment by PeterWone** [comment]
I'm not going to do this in the foreseeable future so I'm going to close the issue. I have retained the idea in my backlog.
