### ISSUE TITLE
Print lines enhancement

### ISSUE THREAD

**Issue by flynjets** [PeterWone/vsc-print#55]
First thank you for this extension. I would like to request that printed lines numbers not be selectable text. This makes it easier when sharing a PDF to copy only the code. For an example of what i'm talking about you can reference the PrintCode implementation of printing line numbers.

**Comment by PeterWone** [comment]
The way PrintCode handles line numbers 

* is incompatible with a hanging indent presentation when a line wraps
* does not reflow correctly when margins, paper size or paper orientation are changed in the print dialog

I tried making the line number containers unselectable using CSS. It works in a web page but does not survive conversion to PDF via printing, so that's not a solution.

This is an open source project. If you find a solution that doesn't cause problems for other users then I would be delighted to test it and release a credited update.

**Comment by PeterWone** [comment]
SVG -- I just did a manual test of using SVG numbers. It works, but only if you _draw_ the letters. If you use an SVG text element the text is selectable.

**Comment by PeterWone** [comment]
I have just noticed that when pasting from PDF comments lose the double slash and line breaks are introduced. I hereby declare this an unsupported application.
