### ISSUE TITLE
Printing not working

### ISSUE THREAD

**Issue by m-born** [PeterWone/vsc-print#58]
Hi Peter,

First off, this is my first issue ever opened on GitHub, so if this is not the right way to turn to you, please let me know and do excuse.

The issue: I just installed VS Code Printing and tried my first print but get the below error message instead. (System: VSC 1.45.1, Win 8.0, FF 76.0.1, Xampp 3.2.4.) 

Thank you for any hint!

```
TypeError: Cannot read property 'render' of undefined
	at c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:172:30
	at Generator.next (<anonymous>)
	at c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:4:12)
	at getRenderedSourceCode (c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:158:12)
	at c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:253:46
	at Generator.next (<anonymous>)
	at c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:4:12)
	at Server.<anonymous> (c:\Users\me\.vscode\extensions\pdconsec.vscode-print-0.7.14\out\extension.js:248:63)
	at Server.emit (events.js:208:15)
	at parserOnIncoming (_http_server.js:735:12)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
```

**Comment by m-born** [comment]
This behavior both when clicking the icon in the top bar and via the context menu on a selection in an open file. 

In the context menu in the file explorer the "Print" menu item is not shown.

**Comment by PeterWone** [comment]
This is the preferred way to contact me with VS Code issues.

In response to this issue I checked that I have the same build of VS Code (yes) and that VSC Print works for me. It does. Next step was getting FF76 and re-testing. No problem occurs. But if the Print menu item does not appear then the extension is not correctly initialising.

The only significant way in which your setup differs from mine is Windows 8, but that shouldn't make any difference. I can only surmise that either somehow your installation is corrupted or there is some kind of freaky permission problem inhibiting library loading. 

- What method of installation did you use?
- Can you get it to work on any other of your computers?

**Comment by m-born** [comment]
Hi and thank you, Peter. 

I installed in the same way as you would have, subsequently reloading the editor. On finding the error, I quit and restarted VSC, but to no avail. 

I have no other machine near me but I will try and un- and re-install the extension, and quit and restart VSC before and after. It may be some while until I get to it but I will report.

Thank you!

**Comment by PeterWone** [comment]
One other thing, there's exactly one line in the app that invokes a method 'render' and the code leading up to it looks like this

```
	if (printConfig.renderMarkdown && fsPath.toLowerCase().split('.').pop() === "md") {
		let markdownConfig = vscode.workspace.getConfiguration("markdown", null);
		let raw = fs.readFileSync(fsPath).toString();
		let content = md.render(raw);
```

As you can see it's preparing to render markdown so I assume you are trying to print markdown?

**Comment by m-born** [comment]
That is in fact so. What may be done re: this? On my very singular side, it would be fantastic not having to convert into another language for printout since what I'm working on is really a research text, for structuring which I have "co-opted" the MD syntax and the particulars it offers.

**Comment by PeterWone** [comment]
Can I ask what is the language you are using when the error occurs? It shouldn't make any difference but clearly _something_ is wrong. It is a source of considerable pride that vsc-print works on all platforms and in every tested language. 

But my ability to test with foreign languages is limited, so I am dependent on assistance from users like you. If you're feeling keen I would be grateful if you did the following:

1. Uninstall vsc-print
2. Clone the fork the repo and clone it to your machine
3. Open the project in VS Code and run it

Because it's an extension project, running it should launch another instance of VS Code that loads the extension in debug mode. This will allow you to see what the error is and tell me more information, and then I may be able to help.

**Comment by m-born** [comment]
Thank you Peter. I uninstalled the extension. To make sure the next steps go right (you intuit well in pointing to the question of my expertise): Do I initiate a repo on my machine and clone this one to there using the URI behind the clone button on this Github front page? (I.e., I'm not sure what the "fork" step includes.) Thank you

**Comment by PeterWone** [comment]
Whether you fork or not depends on whether you intend to make the fix yourself. It seems like your skill level won't allow that, so we can skip that part.

I have to leave for a wedding very shortly but I will write instructions tomorrow. For me it is just after lunch here so that means about 24hrs before I have time to do this.

**Comment by PeterWone** [comment]
OK, your first guess was right. You clone the repo using the URI offered by the clone button. Here it is for your convenience https://github.com/PeterWone/vsc-print.git

1. Copy the URI
2. In VS Code press `F1` then type `git clone` and press Enter. 
3. Then paste the URL and press Enter again.
4. Browse to the location where the project folder is to be cloned. If you choose C:\temp then git will create C:\temp\vsc-print
5. VS Code will offer to open the new repository folder. Accept the offer.

At this point you have cloned the repo but you don't have the dependencies installed.

6. Type Ctrl+` to open the Terminal pane in VS Code. It should open with the path already set to the project folder.
7. Issue the command `npm i` and press Enter. This should install all the dependencies. There is a lot of activity and it can take a few minutes.

It will report a surprising number of vulnerabilities due to flaws in libraries on which vsc-print depends. Don't let these alarm you, they apply primarily to use of the libraries in web pages. I give a lot of thought to this. If you are curious the command `npm audit` will provide further information.

At this point you are ready to run. You don't need to configure launch.json because I've already done that. You can just press `F5` to launch another copy of VS Code in such a way that it loads the extension and runs in the debugger.

**Comment by m-born** [comment]
Hey Peter, thank you very much. I am just in the hot phase of my project submission so let me come back to this as soon as my concentration can be fully with you. Will be back

**Comment by PeterWone** [comment]
Don't forget your issue! It worries me that there might be a defect in VS Code Printing, and with the problem not occurring on any of my systems I cannot pursue it without your support.

**Comment by PeterWone** [comment]
In the absence of further information I cannot pursue this issue. If anyone can add anything I will consider reopening it.
