### ISSUE TITLE
incorrect coloring for html comment across multiple lines 

### ISSUE THREAD

**Issue by alan7872** [PeterWone/vsc-print#63]
I am printing an html file in which there are comments for the form 

1. `<!--comment-->`

2. `/*comment*/` 

But only the first line of the comment is correctly colored as comment.

**Comment by PeterWone** [comment]
This is a shortcoming of the syntax colouring library rather than VS Code Printing.

If you can give me a sample that demonstrates the problem I'll be happy to log a bug with the syntax colouring project.

**Comment by alan7872** [comment]
Below is an html sample together with the PDF printout that demonstrate the problem.

[https://drive.google.com/drive/folders/1SuTVZryAV9MVRucQ3zmbocVW_Od7WVet?usp=sharing](https://drive.google.com/drive/folders/1SuTVZryAV9MVRucQ3zmbocVW_Od7WVet?usp=sharing)

**Comment by Neohiro79** [comment]
Just saw this conversation as a matter of interest. Since I cannot access your HTML Sample, this is just a blind guess here, but you might want to check:

**This is the HTML Code:**

![VSC-Code](https://user-images.githubusercontent.com/18111492/99776958-ea48a580-2b11-11eb-8040-43ea6da9ca0d.jpg)

**This would be the output (and the wrong /\* HTML-comment \*/ won't show up colored):**
![Printout-Style](https://user-images.githubusercontent.com/18111492/99777059-0e0beb80-2b12-11eb-99ed-f08dc6c661fc.jpg)

It might solve your request - in that case this is NOT a bug - this is a wrong HTML comment.

**Comment by Neohiro79** [comment]
Sorry, my fault, I have overlooked that you meant "over multiple lines", which also triggers the same no-syntax problem as meantioned above (the wrong HTML comment). 

**I've made a JSFiddle to first see what happens when using "highlight.js" and if this is a bug related to highlight.js:**

> http://jsfiddle.net/neohiro79/5x13L0hm/3/

---

**The output there seems fine to me - except the fact that it won't show HTML comments - even when HTML is set as class.**

But when used through the plugin, it shows this (which looks like a bug inbetween somewhere):

**VSC Input VS Extension Output:**

<img src="https://user-images.githubusercontent.com/18111492/99781471-30a10300-2b18-11eb-9d33-bdd81791bd3d.jpg" alt="_" width="50%"
/><img src="https://user-images.githubusercontent.com/18111492/99781496-35fe4d80-2b18-11eb-8f21-d21e7d8b98d8.jpg" alt="_" width="50%"
/>

**Comment by PeterWone** [comment]
There are two modes, manual and auto. I use manual whenever VSCode has a definite langId, and for an HTML that is the case. But that doesn't explain the behaviour you're seeing so I suppose I'll have to spin it up in the debugger and seen exactly what's being sent to highlight.js

**Comment by Neohiro79** [comment]
Interestingly, I can't get this s* to work, even when trying to follow the rules:

> see: http://jsfiddle.net/neohiro79/5x13L0hm/19/

---

**When using "HTML" only it won't show ANY comment at all ... for whatever reason.**

**Comment by Neohiro79** [comment]
Peter I've also tried to do it with Prism, but I've ran into similar troubles.

I've already opened a ticket:
> https://github.com/PrismJS/prism/issues/2651

You can see my tryouts in this JSFiddle here:

> http://jsfiddle.net/neohiro79/5x13L0hm/45/

**Comment by Neohiro79** [comment]
I've tried to make it happen in PrismJS, but still things are messed up a bit:

> http://jsfiddle.net/neohiro79/m2xfdqua/2/

**Comment by Neohiro79** [comment]
Digging into the rabbithole ...

Even this nice looking approach
> https://asvd.github.io/microlight/

won't work as expected:
> http://jsfiddle.net/neohiro79/zbfdhxjy/5/

Issue has been submitted, but I guess he might not answer, seems like a dead git repo to me:
 > https://github.com/asvd/microlight/issues/12

... to be continued ...

**Comment by PeterWone** [comment]
Without wishing to rain on your parade, highlight.js is probably as good as it gets. Stackoverflow just switch to using it. 

This is why, despite otherwise being a bit perfectionist about vscode-printing, I think we should let the open-source division of problems thing work for us. Gather your evidence and just log a case with the highlight.js people. We can't do everything and they know their codebase.

**Comment by Neohiro79** [comment]
**Finally I got some feedback for rainbow.js:**

This works PERFECTLY NOW:
> http://jsfiddle.net/neohiro79/zbfdhxjy/6/

**If you want to include all you can use this command here for a build:**
`gulp build --languages=all`

That might also address potential performance issues ...
I know you like highlight.js but it might be worth a try ...

**Comment by Neohiro79** [comment]
**To bundle Craig told me this:**
> The best bet is using gulp build to create a custom bundle and passing whatever languages you want in a list. 
> You can also use the bundler from the rainbow website, but it is using a slightly out of date version of rainbow (long story) 
> http://rainbowco.de

**Comment by Neohiro79** [comment]
So Peter, as thought, don't expect 'help' from the guys from highlight.js, as seen in the comment here:

https://github.com/highlightjs/highlight.js/issues/2884

It seems to me they have the very same attitude than we're well aware of the superior VSC forum feedback in our case.

Since I've made that research for various reasons so comprehensive, I'll personally stick with **[rainbow.js]**(https://craig.is/making/rainbows) since it not only seems **the most reliable code syntax highlighter on the market right now**, 
it also has the nicest and most helpful developer feedback I've encountered so far!

Hope you can find a solution which finally works - give it a try!

**Comment by Neohiro79** [comment]
**The answer came promptly after telling them that it obviously works in rainbow.js, so this is how it "only-works" in highlight.js:**

> https://jsfiddle.net/neohiro79/zbfdhxjy/12/

That said, I still prefer the rainbow.js solution, since you do not need to "mask" anything to make it work, since I don't get the whole "I am concerned about security issue" in this specific regard:

> https://github.com/ccampbell/rainbow/issues/249

Hope that helps.

**Comment by joshgoebel** [comment]
> So Peter, as thought, don't expect 'help' from the guys from highlight.js, as seen in the comment here:

@Neohiro79 FYI: This is the attitude I picked up on that *very slightly* miffed me. :-)   

**Just to explain here we do not highlight unescaped HTML code because it is a HUGE security risk and a very bad idea.**  _This is a major feature, not a bug._  If you want HTML code to be treated as "text" and highlighted, it must be properly escaped. Otherwise google "html injection", "javascript injection", etc...

IE:

```html
<code>
&lt;code&gt;this is a code tag to be highlithed&lt;/code&gt;
</code>
```

I personally believe Rainbow is buggy in this regard or at the *very least* encouraging/enabling people to make some very poor security choices.  I've explained this as clearly as I can to the author and we'll see what he decides. :-)  With a very small change to his library he could close this security hole and prevent people from shooting themselves in their own foot.

**Comment by joshgoebel** [comment]
@PeterWone I'm not sure if this affects your plugin or not... if you are asking us to highlight code inside a block you need that code to be properly HTML escaped (which should be pretty trivial to do with JS).  The block should not include RAW unescaped HTML - which we are not going to highlight.

**Comment by Neohiro79** [comment]
**@josh** :-) big hug for all your effort !!!

@Neohiro79 FYI: This is the attitude I picked up on that very slightly miffed me. :-)

Yeah, I got the point, that's what I thought ... but you also opened up for us 'beginners' now, which makes me happy :-)

**Comment by PeterWone** [comment]
So in essence if I escape HTML the issue vanishes and we could consider using your library.

Bring back Windows Phone

________________________________

**Comment by joshgoebel** [comment]
**That is my current understanding, yes.**  Highlight.js (currently) preserves HTML - it's passed thru silently - while the actual TEXT content is highlighted... so it pretty much "disappears"... this is legacy behavior and in the future we'll likely drop it completely but we can't do that until version 11.  If you want all the content to be treated as text (And highlighted) then just escape it.

**Comment by Neohiro79** [comment]
Oh, that explains why some of them won't show the `html` tags but the content, they used innerText only to get the markup of that specific container right?

**Comment by joshgoebel** [comment]
> Oh, that explains why some of them won't show the html tags but the content, they used innerText only to get the markup of that specific container right?

Yes, or `textContent`.

**Comment by Neohiro79** [comment]
So the issue with rainbow.js is that they use innerHTML instead of textContent to "get all the code" they want to highlight and inject it back into the given container - so basically if the HTML is malicious in first place it will keep beeing malicious with the additional highlighting, correct?

**Comment by joshgoebel** [comment]
> So the issue with rainbow.js is that they use innerHTML instead of textContent to "get all the code" they want to highlight and inject it back into the given container - so basically if the HTML is malicious in first place it will keep beeing malicious with the additional highlighting, correct?

Well, no.. :-)  It's quite likely Rainbow would actually "fix it"... by turning it into "NOT HTML"... but it's quite possibly too late... the HTML is loaded BEFORE Rainbow sees it.  The JS runs BEFORE Rainbow sees it.

```js
<pre><code>
<script>
// this code runs BEFORE Rainbow
// this code could even hack Rainbow and prevent it from loading if it wanted to
</script>
</code></pre>

```

**Comment by Neohiro79** [comment]
Yeah, got it.

But this also means (to me) that weather Rainbow.js nor Highlight.js can ever prevent anyone from injecting "bad javascript" (of course) which will anyway beeing executed BEFORE any of those methods through the browser engine, weather innerHTML nor textContent nor any masking techniques beeing applied by any javascript library afterwards, will ever come into play.

Meaning that the main problem I still see is that it can only "warn" a user AFTER potential malicious code was injected already, or in other terms, it is much more important to warn users that they shall never use untested or unknown php code which might be used in a contact form or a comment form of any plugin since they do not know weather or not this code is beeing properly masked BEFORE it even hits the html page - which in turn will execute the script BEFORE EVEN ANY highlighter script can detect something via innerHTML or innerText - or am I wrong?

**Comment by joshgoebel** [comment]
@Neohiro79 Right, we can't STOP an injection attack like this "in the wild"... but if someone is building their project and testing things out and they do this accidentally **we can yell at them very loudly then** - so they fix it early - hopefully before their code every gets out "in the wild"...

**Comment by Neohiro79** [comment]
Yeah, got you.

**Comment by Neohiro79** [comment]
I'll work on a html warning page and provide it to you once I finished which can be used to be injected into the document or as a popup for all to be aware of once they use HTML code in plain form - since I really think this is a problem since not everyone is aware of this shit. 

You can sent me the text you might think or come up with, I'll see what I can do, to make it strikingly clear for others.

**Comment by joshgoebel** [comment]
I don't need anything from you.  We have an issue to track this, but we can't do anything about it until 2021 anyways - because we can't break  the existing behavior in v10.  If you wanted to drop some text on that issue you could, but we'll likely think about this carefully when we get around to doing it. So you can save the time.

**Comment by Neohiro79** [comment]
Sure, if there's no help needed I won't help of course. It was just a proposal with a good intension after all.

**Comment by PeterWone** [comment]
OK so looking at the code (it's been a while) I have a function getSourceCode which ultimately either loads the content of a file or grabs the buffer of the active editor. A string comes back. It could contain _anthing_ and it _could_ be toxic.

I give highlight.js a crack at it 

```ts
  let sourceCode = await getSourceCode();
  let renderedCode = "";
  try {
    renderedCode = hljs.highlight(sourceCode[0], sourceCode[1]).value;
  }
  catch (err) {
    renderedCode = hljs.highlightAuto(sourceCode[1]).value;
  }
```

and as you can see if I cannot map the language to something `highlight.js` can digest then I let `highlight.js` off the leash and let it make up its own mind.

This _does_ have the vulnerability we discussed, both for accidentally toxic code and for handling the work of others.

@joshgoebel do I understand correctly that for HTML you _want_ me to escape all angle brackets to to `&lt;` and `&gt;` before passing the HTML to `highlight.js`?

**Comment by joshgoebel** [comment]
> This does have the vulnerability we discussed, both for accidentally toxic code and for handling the work of others.

I was never asking you to do anything magic, just upgrade to v10, which fixes many of the issues. :-)  If our library still have regex issues, then yeah it's possible you'll find them - but that's on us, not you. :-)

>do I understand correctly that for HTML you want me to escape all angle brackets to to &lt; and &gt; before passing the HTML to highlight.js?

That's only if your HTML is *already on the page* inside a block, etc... if you're using the API functions directly then you pass them normal regular text/code whatever... there is zero need to do any type of escaping here.

**Comment by PeterWone** [comment]
@joshgoebel  Well then... v10 here we come.

**Comment by PeterWone** [comment]
Well, regression tests all pass. I'm pushing out 0.8.3

**Comment by Neohiro79** [comment]
Thanks again Josh (whoever you are :-))

**Comment by PeterWone** [comment]
@Neohiro79 0.8.3 should appear soon. Let me know if you encounter any glitches.

**Comment by Neohiro79** [comment]
Seems to still have some `highlight-troubles` when it comes to multiline comments :-(
![still-problems-with-multiline-comments](https://user-images.githubusercontent.com/18111492/99901203-2f590d00-2cb5-11eb-82e3-b6a755d4e913.jpg)

**Comment by PeterWone** [comment]
It's not the end of the world. We can look into rainbow etc but I don't want to lose the auto detect capability because I need it for unsaved files

**Comment by joshgoebel** [comment]
What trouble?  I’m pretty sure that we highlight regular HTML code including comments very well.

**Comment by Neohiro79** [comment]
**@joshgoebel** It looks like the multiline comments won't get highlighted properly, the first part is green `<!--` the last part is grey `-->` as far as I can see in the screenshot.

**Comment by PeterWone** [comment]
As well as being a different colour,  the first line of the multiline comment in Neo's screen grab is italicised whereas subsequent lines of the comment are not italic.

It's this eye for detail that makes Neo one of my most valued contributors. I might never have noticed on my own.

**Comment by Neohiro79** [comment]
Yeah, you're right **@peter**, even me didn't saw that one coming ;-) 

... indeed it's italic, the first `<--` three chars

**Comment by Neohiro79** [comment]
Thanx for the compliment by the way, I give my best to annoy everyone, including myself from time to time :-)

**Comment by joshgoebel** [comment]
<img width="529" alt="Screen Shot 2020-11-22 at 2 27 49 PM" src="https://user-images.githubusercontent.com/6473/99914987-f037b580-2cce-11eb-8845-833a672cd972.png">

Pretty sure that's not our bug, we know how to highlight basic XML pretty well. :)

**Comment by joshgoebel** [comment]
Perhaps you're using auto detect and not the XML highlighter?

**Comment by Neohiro79** [comment]
**Here is an example of XML highlighter usage:**

> http://jsfiddle.net/neohiro79/zbfdhxjy/31/

**Comment by Neohiro79** [comment]
**@josh** Is it correct to use the `vbscript-html.min.js` include for proper html highlighting or is there another one - because that's the only one I've found on the CDN ... ?

**Comment by Neohiro79** [comment]
> You can also control the size precisely if you throw out a few large languages that no one is probably using. Using all 190 is probably overkill.

Also, which subset of precompiled language scripts you would recommend out of all 190 different ones?

**Comment by joshgoebel** [comment]
> @josh Is it correct to use the vbscript-html.min.js include for proper html highlighting or is there another one - because that's the only one I've found on the CDN ... ?

`html` (an alias of `xml`)... But using `vbscript-html` wouldn't mess up like what you are showing.  It just uses XML internally plus allows for VBScript tags (if they are around).

> Also, which subset of precompiled language scripts would you recommend out of all 190 different ones?

We have a "common" set, but now way to get at that easily via Node.js (that should probably be added).  If you really want to know you could download the web version and grep it for "registerLanguage" and you'd see the list.

**Comment by joshgoebel** [comment]
> Here is an example of XML highlighter usage:

Yes looks perfect to me, unless I'm missing something?

**Comment by Neohiro79** [comment]
> We have a "common" set, but now way to get at that easily via Node.js (that should probably be added). If you really want to know you could download the web version and grep it for "registerLanguage" and you'd see the list. But there are lots of things common doesn't include... if you're going to make a sublist you should probably eyeball it.

**@ josh** So you mean that basically we have to cherrypick the languages from the github source 

> https://github.com/highlightjs/highlight.js/tree/master/src/languages

and then bundle them together to an individual `VSC-build` for the most used languages in this very editor?

**That's the source I've found and used:**
> https://cdnjs.com/libraries/highlight.js

**Comment by Neohiro79** [comment]
By the way `html` is not in this repo, only `htmlbars.js` and the previous mentioned `xml` which would be the correct one to use for html, css and javascript in this case then?

---

![html-lib](https://user-images.githubusercontent.com/18111492/99918930-847b3a00-2d1a-11eb-99e2-8d2445efaba4.jpg)

---

**From:**
> https://github.com/highlightjs/highlight.js/tree/master/src/languages

**Comment by PeterWone** [comment]
That's why I ship all of it and use the vs code language identifier with a fallback to auto. 

It is possible for extensions to register new language identifiers and there is no reason to expect them to be consistent with highlight.js but auto means that oddball things like Swift and Kotlin work. 

@joshgoebel indulge my curiosity, do you support APL?

**Comment by joshgoebel** [comment]
@Neohiro79 Open the xml file and read it at the bottom. `xml` and `html` are the same thing.  If you're loading them via CND then you want `xml`.  But it "includes" `html` because the same grammar works for both.  And in your HTML `language-html` and `language-xml` are exactly the same.

> do you support APL?

Can you expand that acronym please?

**Comment by Neohiro79** [comment]
**@ josh** I really don't want to be pedantic here, but when I've searched in the CDN for `html` I found nothing than this `vbscript-html.min.js` which I used (and it works, I know). In no way I would've come to the conclusion to specifically search for `xml` - eventhough that might be the 100% correct technical term for that specific syntax style - but it would also make really sense to me to rename this into `html-xml` or `xml-html` at the very least, 

I mean this way one can find it when searching for it. 

Who looks into a language description file when searching for the language - and even more - at the `bottom` of it, just to see if there is a `hint` for any potential `language-alias`?

But now you've mentioned it, yes, sure, I know where to look when I am not sure about the usecase of a specific language file.

**Comment by Neohiro79** [comment]
**@ peter** from **@ josh**

> do you support APL?
> Can you expand that acronym please?

**Comment by joshgoebel** [comment]
This is why we have:

https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md :-)

> but it would also make really sense to me to rename this into html-xml or xml-html at the very least,

That isn't something we could do until v11 in any case since it would break things for existing users.  There are perhaps some other things worth discussing around HTML vs XML though - could you file an issue with that suggestion?

> Who looks into a language description file when searching for the language - and even more - at the bottom of it, just to see if there is a hint for any potential language-alias?

That was more to show you how it works. :) Then I went and pasted the list for you instead.

**Comment by Neohiro79** [comment]
Thanx, yes - but I saw even in the list someone thought the same than me:

![HTML-XML](https://user-images.githubusercontent.com/18111492/99920918-1721d600-2d27-11eb-81c6-687b4b5d1ae1.jpg)

:-)

Sure, I'll will file an issue on highlight.js for that specific request.

**Comment by Neohiro79** [comment]
And this list would of course IMHO make sense to be put in the same folder here:

https://github.com/highlightjs/highlight.js/tree/master/src/languages

since I didn't know of that list before that it even exists.

**Comment by Neohiro79** [comment]
Just as an idea, having for example three basic subsets, one that is optimised for `xml-html-css-js` usage, one that is bundled for `some-broad-but-special-programming-languages-used` and one that is the `full metal jacket` release - which should only be used in rare cases of course - would be so much more convenient ...

and for those `geeks` and `nerds` who really love to look into each file and tweak the shit out of everything there still is the option to `bundle` the language-files individually.

Just my two cents.

**Comment by joshgoebel** [comment]
I don't think the uses cases are that clear at all - that's why we make it so easy for people to download what they need instead of making that choice for them:

https://highlightjs.org/download/

And if you want to common on the 'common' list especially there is an issue open for any changes we might make there in 2021.

**Comment by Neohiro79** [comment]
But it wouldn't hurt either to promote at least a carefully chosen preset package, I mean ...

**Comment by Neohiro79** [comment]
It's like HTML in the beginning - "strict" "transitional" and "frameset", three basic choices

**for example for web**
HTML - CSS - JS - PHP - SQL

**for example the most used ones (for programming):**
HTML - CSS - JS - PHP - SQL - PYTHON - JAVA - BASH/SHELL/POWERSHELL / C# / C++ / C / Typescript

**and the full package**

**AND THE INDIVIDUAL CHOICES / BUILDS**

**Comment by joshgoebel** [comment]
The existing "common" build is small enough to serve for "both" the cases you just list at just 36kb.

**Comment by Neohiro79** [comment]
Oh I see. I haven't recognised those "headlines". Yeah, but it's kinda huge package for "just the web" ...
It for sure serves well for the programming fraction like you - sure - but not for "just the simple web package" (seems like a huge language overkill to me).

I mean I don't want to spend hours of finding out which language packages to use to just highlight my basic code examples in my webpage and even then I later figure out, that I might used the wrong ones or could've used better ones - I hope you get what I mean or want to tell you here.

**Comment by Neohiro79** [comment]
For example, right now I use this in my first testcases, because I didn't even realised `common` existed:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.5/highlight.min.js"></script>
<srcipt src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.5/languages/vbscript-html.min.js"></srcipt>
<srcipt src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.5/languages/css.min.js"></srcipt>
<srcipt src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.5/languages/javascript.min.js"></srcipt>

<script>hljs.initHighlightingOnLoad();</script>

```

**Comment by joshgoebel** [comment]
There might be a docfix here (to better explain the CDN and default built-ins), but right now I'm not convinced more and more variants is the answer. :)

**Comment by Neohiro79** [comment]
The fun-fact is, I didn't even know that there are variants. I just thought you need the basic lib and then the specific language packs named after their language.

**Comment by Neohiro79** [comment]
By the way, see, even after 15 minutes research of how to implement `highlight.js` properly, I used it wrong - or at least implemented useless scripts.

Please consider at least a web-package. You will see in the stats, how often it will be picked and used.

Or just include this basic web-package in the highlight.js file itself and meantion that you don't need any .css/.js/.xml language pack at all to start with. Only those "additional" languages - I don't know. It's way to hard to figure it out as a beginner.

**Comment by Neohiro79** [comment]
**@ josh** Am I understanding this right:

**highlight.js already packages this 'common' bundle within itself???**

> In that case you only need the first line.

**At least it seems to work here right now:**
http://jsfiddle.net/neohiro79/zbfdhxjy/32/

![common-bundle](https://user-images.githubusercontent.com/18111492/99930374-20c03380-2d51-11eb-8b82-3cb4832f78bd.jpg)

> The existing "common" build is small enough to serve for "both" the cases you just list at just 36kb.

**So all this is already bundled within the highlight.js file itself?**

![common-content](https://user-images.githubusercontent.com/18111492/99930361-19992580-2d51-11eb-9582-b541d7a75169.jpg)

**Comment by PeterWone** [comment]
Yes, they are all bundled by webpack. 

APL is the name of a programming language. It stands for A Programming Language. Really. https://en.wikipedia.org/wiki/APL_(programming_language)

**Comment by Neohiro79** [comment]
Well, than I guess, my whole effort was for nothing to convince **@Josh** here to make a webpack-bundle ;-)

... was worth a try when not knowing that it already includes all that languages from start.

But what if I want only those three languages (like a `light version` of your full-blown-highlighter - in that case I just use the language pack and no `highlight.js` at all? - because else it makes no sense to me to provide those single language files via CDN ...

**Comment by Neohiro79** [comment]
Did you find the problem **@Peter** ?

It might be a setting of the correct "classname" - maybe? 

Can you show the code to **@josh** that he might find out what the problem is?
Or paste the questionable part on his service for 24h - http://pastie.org?

**Comment by PeterWone** [comment]
Your efforts to improve the quality of the product are never a bad idea. 

To understand why I bundled all of it you must consider the fact that VS Code Printing is designed to work offline.

To install a user selection would require either a VSIX that supports some mechanism for choosing during the installation process (I don't think this is possible) or a fancy download page that builds a custom VSIX according to selections on a web page.

Due to the overheads of handling loads of small files it's actually _faster_ to load an 835KB containing all of highlight.js than it is to demand load parts of it and all its dependencies. No I haven't time today. It's my first day at a new job.

**Comment by Neohiro79** [comment]
Sorry, might has been a bit chaotic, the proposal for the bundling was originally meant for **@josh** (the whole webbundle thing).

Yeah sure, no hurry, good luck on your new job!

**Comment by PeterWone** [comment]
I have a strong suspicion that this is actually caused by the problem in #78 which is about to be resolved.

**Comment by PeterWone** [comment]
We combine "hanging indent" for line numbers with PRE for code indent by using a table and putting the PRE in a TD. 

There is an implicit assumption in this that the code is strictly line based and that any markup tags introduced by highlight.js will both open _and close_ on the same line, a line being defined by \n rather than wrapping. Mutli-line comments and string literals break this assumption and to fix it we have to parse the rendered HTML looking for unbalanced tags, close them at the end of the line and re-open them at the start of the next.

**Comment by PeterWone** [comment]
@joshgoebel note the above comment -- this is not a `highlight.js` problem.

**Comment by joshgoebel** [comment]
> we have to parse the rendered HTML looking for unbalanced tags, close them at the end of the line and re-open them at the start of the next.

Yep.  You got the idea.  If you do it abstractly enough you should make a plugin for it. :)

**Comment by PeterWone** [comment]
@alan7872 thanks for opening this can of worms. We finally got to the bottom of things.
