### ISSUE TITLE
localhost webserver remains running

### ISSUE THREAD

**Issue by djradon** [PeterWone/vsc-print#79]
It seems a little creepy to continue exposing the web page (indefinitely?) on http://localhost:37151/ -- even after printing is finished. Is there a way to shut down http://localhost:37151/ ?

**Comment by PeterWone** [comment]
It does but that doesn't work properly on all browsers. What are you using? Look in your settings.
![image](https://user-images.githubusercontent.com/5498936/110078426-733ed080-7dd3-11eb-98a0-e7c75559121a.png)

If print and close is ticked and it stays open then my guess is you are using Firefox.

**Comment by djradon** [comment]
Yup, Firefox. Love the idea, very cool tool to have in the toolbox. And thanks for the response... I see now that's in your release notes,

**Comment by PeterWone** [comment]
Note also that I support printing with a browser that is not your default browser. Install a Chromium derivative and you can use it just to print, which will fix the issue.

**Comment by djradon** [comment]
feature-idea: You could have a "cancel print service" command for manually turning it off.

**Comment by PeterWone** [comment]
I thought about a long timeout but some people sit there looking at the preview for ten minutes then hit print. I suppose I could load a "done" URL just before closing the browser to close the loop.

**Comment by baincd** [comment]
What about a timeout setting?  For example if set to 30, then the webserver is shut down after 30 secs.  If zero (or blank?), then the webserver does not shut down.  This would allow users to decide how long they want to keep the webserver running, or even not shut it down if they prefer.

**Comment by PeterWone** [comment]
I'm thinking about implementing a request handler so that just after printing the browser requests a specific url, and this request tells the webserver to exit.

**Comment by baincd** [comment]
What about if the user doesn't actually print from the browser?

**Comment by PeterWone** [comment]
You mean the case where Print and Close is unchecked in the settings and the page just opens in the browser? In that case the user is probably testing a stylesheet and would appreciate the webserver  remaining active.

**Comment by PeterWone** [comment]
This isn't a big issue. 
* It's on a random port that won't be port-forwarded. 
* It doesn't survive closure of VS Code.

I might add some code to prohibit back-pathing in URLs if I haven't already, but apart from that all you can request is the last print job and static resources that the current user can access.

**Comment by baincd** [comment]
I believe this is a significant issue.  I may not want someone else on the same network to be able to port scan and see what I've recently printed.  Also it is better to have a defense-in-depth strategy, and not just depend on a properly-configured firewall and obscure port. 

This is why I was thinking a timeout - I assume it wouldn't be difficult to implement, and users can decide for themselves how important this is to them.

**Comment by PeterWone** [comment]
If you want it handled on your timetable then submit a PR.

**Comment by PeterWone** [comment]
@baincd It might be better to restrict requests to the local machine

**Comment by baincd** [comment]
I think restricting requests to the local machine is a good idea.  Should this change be made, I think it might also be a good idea to note it in the README as well since this behavior isn't obvious.  That should help allay some user's concerns.

Even with this change, I still think it's worth adding an optional timeout though.  That way, any user who is concerned about the webserver running would have the option to have it automatically shutdown.  The default could be to have the timeout disabled so there is no change in the default behavior.

(On a slight tangent, it might be worth noting in the README that Chrome offers the best user experience.  I see now it is noted in the README under 0.6.2 in the release notes, but only users who read through all the release notes will see that.  I was using Firefox until I started researching this a bit and came across some of your comments here and on another thread.  I tested the extension to use Chrome and discovered Chrome definitely provides a much better user experience!  I think it would be worth calling that out in the README so more users are aware of that.)

I do hope to find some time to look into this in the next week or two.  (For any user who concerned about this issue in the meantime, note that running the command "Developer: Reload Window" will shut down any webservers started by this extension)

**Comment by baincd** [comment]
I have 2 PRs submitted to thoroughly remediate this issue.

#92 - this adds a timeout on the server (default to 30 seconds, can be disabled)

#93 - This only allows connections to localhost (needs to be tested on more configurations before merging).

**Comment by PeterWone** [comment]
I'm closing this because @baincd addressed it with his PRs which were duly merged.
