### ISSUE TITLE
No documentation for WSL support

### ISSUE THREAD

**Issue by drkvogel** [PeterWone/vsc-print#95]
In the release notes, WSL support is mentioned, but I can't find any details of how to use it.

> 0.7.14
> Issue 51 - add configuration in support of WSL, courtesy of sburlap 

I tried printing from VS Code running in Windows, connected to a folder in WSL with the "Remote - WSL" extension, and it opened the file in a Firefox window running in WSL, rather than Windows, with the option to Save to PDF. I was hoping I could run Print from VS Code in Windows with a file in WSL open and print it out to a connected printer in Windows.

Perhaps the WSL support at the moment means it supports VS Code running in WSL being able to print within WSL, but I can't find any docs that explain what the WSL capabilities are or how to use them.

**Comment by PeterWone** [comment]
Chris, this one was a user contribution. While I have do WSL installed, Linux isn’t my thing and I’m really not able to assess it because I don’t really understand what it’s supposed to do.

As far as I can tell, WSL is a bit like the Windows on Windows thing that used to let you run Windows XP software on later versions of Windows, with the software running on a virtual machine but the UI appearing as first class windows on your desktop.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Chris ***@***.***>
Sent: Saturday, 3 April 2021 9:48 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [PeterWone/vsc-print] No documentation for WSL support (#95)


In the release notes, WSL support is mentioned, but I can't find any details of how to use it.

0.7.14
Issue 51 - add configuration in support of WSL, courtesy of sburlap

I tried printing from VS Code running in Windows, connected to a folder in WSL with the "Remote - WSL" extension, and it opened the file in a Firefox window running in WSL, rather than Windows, with the option to Save to PDF. I was hoping I could run Print from VS Code in Windows with a file in WSL open and print it out to a connected printer in Windows.

Perhaps the WSL support at the moment means it supports VS Code running in WSL being able to print within WSL, but I can't find any docs that explain what the WSL capabilities are or how to use them.

**Comment by drkvogel** [comment]
WSL (Windows Subsystem for Linux) is "a compatibility layer for running Linux binary executables natively on Windows 10", so you can install a full Linux distro (like Ubuntu, which I'm running) within Windows and run Linux programs "natively" instead of in a virtual machine like VirtualBox. There is a translation between the Linux filesystem and the Windows filesystem as they are very different, obviously. You can run VS Code in Windows but, with an extension, connect to the Linux filesystem in WSL. So I have my repos in Linux, but edit them with VS Code from Windows, which works pretty nicely, most of the time. Except I can't print, which I hardly ever need to do, but did just recently.
